### ISSUE TITLE
The skin "Lano-Visualizer\visualizer.ini" does not contain any meters and will be deactivated.

### ISSUE THREAD

**Issue by kirankunigiri** [MarcoPixel/Lano-Visualizer#24]
It was originally loading properly, but when I was trying to make a new layout and loaded the skin again, it says this:
The skin "Lano-Visualizer\visualizer.ini" does not contain any meters and will be deactivated.

**Comment by kirankunigiri** [comment]
This was fixed by reinstalling. The error occurs again if you change the settings too much, especially the number of bars.

**Comment by EchenCraft** [comment]
This is still an issue but doesnt seem to be changing the settings too much as I set it up it ran fine for months then one day started this... after reinstalling and getting it set up again... a few months pass and again this issue. I literally have no idea why it just randomly starts popping this error as nothing has changed on my system to cause it.
