### ISSUE TITLE
Can't select audio devices other than virtual audio cables

### ISSUE THREAD

**Issue by Iron-Oracle** [MarcoPixel/Lano-Visualizer#4]
Can't pick my audio device

**Comment by marcopixel** [comment]
Thanks for your feedback!

This bug seems to be caused from the AudioLevel plugin and i've made an issue on their github repo. Please follow the progress there as i'm not able to fix it in my skin as this is an Rainmeter issue.

https://github.com/rainmeter/rainmeter/issues/120

**Comment by soFFe** [comment]
I had the same problem - updated to the latest version of rainmeter and it worked now.

Previous Version: Rainmeter 4.0 Final Release
Current, working Version: Rainmeter 4.1 Beta Release - r2876

**Comment by marcopixel** [comment]
Yeah, every version of Rainmeter 4.1 Beta Release - r2876 and upwards fixed this issue.
